### ISSUE TITLE
Cant Install

### ISSUE THREAD

**Issue by fab679** [grand-stack/graphql-architect#6]
wont install there is a problem with url link provided

**Comment by johnymontana** [comment]
Hi @fab679 - what version of Neo4j Desktop are you using? There was an issue that prevented installation, but a fix has been released and upgrading to Neo4j Desktop version 1.3.4 should solve it.

If you are using v1.3.4 of Neo4j Desktop could you include any errors or messages that you're getting?

**Comment by johnymontana** [comment]
Perhaps could also be related to this npm outage: https://status.npmjs.org/incidents/cksjqc1w11v5

**Comment by fab679** [comment]
Thanks alot William i updated my desktop version and it worked. Love neo4j
and its community for your responses,

**Comment by johnymontana** [comment]
OK great - glad you got it installed!
