### ISSUE TITLE
Laggy

### ISSUE THREAD

**Issue by lustig-bakkt** [grand-stack/graphql-architect#8]
Absolutely love the idea of this project, but I'm running into a good bit of lag when running it. 

Are there any settings to tweak, Java versions to check, etc that may help diagnose and fix?

Thanks!

**Comment by jexp** [comment]
Do you have more details on when it is laggy? Ie which operations in the UI?

**Comment by lustig-bakkt** [comment]
Hey @jexp - as soon as I open it up (even on a brand new db) - everything in the app lags. Scrolling and typing in the editor, entering queries in the Playground, etc. 

Let me try on a different computer and I'll report back if I still run into those issues.

**Comment by lustig-bakkt** [comment]
I've moved on to running everything in Docker so don't really have a need for architect. Thanks again for this awesome toolset!
